[package]
name = "debug"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true, features = ["dev"] }
physics = { workspace = true, features = ["dev"] }
runtime = { workspace = true, features = ["dev"] }
widgets = { workspace = true }

bevy = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
winnow = { workspace = true }

[lints]
workspace = true
