[package]
name = "bevy_game_2d"
authors = ["Abigail Moore <abigailmmoore00@gmail.com>"]
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    ".",
    "crates/datagen",
    "crates/game/app",
    "crates/game/assets",
    "crates/game/common",
    "crates/game/controls",
    "crates/game/data",
    "crates/game/debug",
    "crates/game/input",
    "crates/game/physics",
    "crates/game/runtime",
    "crates/game/settings",
    "crates/game/widgets",
    "crates/macros/debug_option_derive", "crates/macros/define_resource",
    "crates/macros/maybe_fields",
]
resolver = "2"

[workspace.dependencies]
bevy = { version = "0.19", default-features = false, features = [
    # Base feature sets
    "2d",
    "audio",
    "ui",
    # Additional features
    "bevy_settings",
    "bevy_state",
    "multi_threaded",
    "reflect_auto_register",
    "serialize",
    "std",
    "sysinfo_plugin",
    "trace",
    # UI and input
    "system_clipboard",
    # Gamepad functionality
    "bevy_gilrs",
    # File formats
    "png",
    # Picking (aka clicking on world objects)
    "sprite_picking",
    # Linux rendering
    "wayland",
    "x11",
] }
const_format = "0.2.36"
derive-new = "0.7.0"
serde = "1.0.228"
getset = "0.1.6"
paste = "1.0.15"
regex = "1.12.3"
ron = "0.12.1"
strum = { version = "0.28.0", features = ["derive"] }
strum_macros = "0.28.0"
thiserror = "2.0.17"

# Compile out low-severity logs to improve performance.
# Remove these features if you want to profile your game with tracy.
# (see <https://github.com/bevyengine/bevy/blob/main/docs/profiling.md#tracy-profiler>)
tracing = { version = "0.1", features = [
    "max_level_debug",
    "release_max_level_warn",
] }

assets = { path = "crates/game/assets" }
common = { path = "crates/game/common" }
controls = { path = "crates/game/controls" }
data = { path = "crates/game/data" }
debug = { path = "crates/game/debug" }
input = { path = "crates/game/input" }
physics = { path = "crates/game/physics" }
settings = { path = "crates/game/settings" }
runtime = { path = "crates/game/runtime" }
widgets = { path = "crates/game/widgets" }

# Proc macro dependencies
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[features]
# Default to a native dev build.
default = ["dev_native"]
dev = [
    "app/dev",
    # Improve compile times for dev builds by linking Bevy as a dynamic library.
    #TODO: Figure out how to run the debugger with this enabled
    #"bevy/dynamic_linking",
    # Improve error messages coming from Bevy
    "bevy/track_location",
    "bevy/bevy_dev_tools",
    "bevy/bevy_ui_debug",
    "bevy/bevy_feathers",
    "bevy/debug",
    "bevy_mod_debugdump",
    "graphviz-rust",
]
dev_native = [
    "dev",
    # Enable asset hot reloading for native dev builds.
    "bevy/file_watcher",
    # Enable embedded asset hot reloading for native dev builds.
    "bevy/embedded_watcher",
]

[dependencies]
bevy = { workspace = true }

bevy_mod_debugdump = { version = "0.16.0", optional = true }
graphviz-rust = { version = "0.9.8", optional = true }

app = { path = "crates/game/app" }


# Compile with Performance Optimizations:
# <https://bevyengine.org/learn/quick-start/getting-started/setup/#compile-with-performance-optimizations>

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

# Remove expensive debug assertions due to <https://github.com/bevyengine/bevy/issues/14291>
[profile.dev.package.wgpu-types]
debug-assertions = false

[profile.release]
# Compile the entire crate as one unit.
# Slows compile times, marginal improvements.
codegen-units = 1
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
lto = "thin"

# This profile will be used by `bevy run web` automatically.
[profile.web-release]
# Default to release profile values.
inherits = "release"
# Optimize with SIZE in mind (also try "z", sometimes it is better).
# Slightly slows compile times, great improvements to file SIZE and runtime performance.
opt-level = "s"
# Strip all debugging information from the binary to slightly reduce file SIZE.
strip = "debuginfo"

# Optimize for build time in CI.
[profile.ci]
inherits = "dev"
opt-level = 0
debug = "line-tables-only"
codegen-units = 4

[profile.ci.package."*"]
opt-level = 0


[package.metadata.bevy_cli.release]
# Disable dev features for release builds.
default-features = false

[package.metadata.bevy_cli.web]
# Disable native features for web builds.
default-features = false

[package.metadata.bevy_cli.web.dev]
features = ["dev"]

[workspace.lints.rust]
# Mark `bevy_lint` as a valid `cfg`, as it is set when the Bevy linter runs.
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(bevy_lint)"] }

[workspace.lints.clippy]
# Bevy supplies arguments to systems via dependency injection, so it's natural for systems to
# request more than 7 arguments, which would undesirably trigger this lint.
too_many_arguments = "allow"
# Queries may access many components, which would undesirably trigger this lint.
type_complexity = "allow"
# Make sure macros use their standard braces, such as `[]` for `bevy_ecs::children!`.
nonstandard_macro_braces = "warn"

# You can configure the warning levels of Bevy lints here. For a list of all lints, see:
# <https://thebevyflock.github.io/bevy_cli/bevy_lint/lints/>
[package.metadata.bevy_lint]
# panicking_methods = "deny"
# pedantic = "warn"