[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
assets = { workspace = true }
common = { workspace = true }
controls = { workspace = true }
data = { workspace = true }
input = { workspace = true }
settings = { workspace = true }
runtime = { workspace = true }
widgets = { workspace = true }

debug = { workspace = true, optional = true }

bevy = { workspace = true }
getset = { workspace = true }
paste = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

crossbeam = "0.8.4"

# TODO: These dependencies are only referenced for debug rendering - remove this as soon as reasonable
physics = { workspace = true }
parry3d = { version = "0.28.0", optional = true }

[features]
dev = [
    "debug",

    "common/dev",
    "runtime/dev",

    "parry3d",
]

[target.wasm32-unknown-unknown.dependencies]
getrandom = { version = "0.4.2", features = ["wasm_js"] }

[lints]
workspace = true